/*
 * This file is generated by jOOQ.
 */
package com.pp.jooq.model;


import com.pp.jooq.model.tables.MetaData;
import com.pp.jooq.model.tables.MetaField;
import com.pp.jooq.model.tables.MetaRow;
import com.pp.jooq.model.tables.MetaTable;
import com.pp.jooq.model.tables.records.MetaDataRecord;
import com.pp.jooq.model.tables.records.MetaFieldRecord;
import com.pp.jooq.model.tables.records.MetaRowRecord;
import com.pp.jooq.model.tables.records.MetaTableRecord;

import javax.annotation.processing.Generated;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * meta.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.15"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<MetaDataRecord> KEY_META_DATA_PRIMARY = Internal.createUniqueKey(MetaData.META_DATA, DSL.name("KEY_meta_data_PRIMARY"), new TableField[] { MetaData.META_DATA.ID }, true);
    public static final UniqueKey<MetaFieldRecord> KEY_META_FIELD_PRIMARY = Internal.createUniqueKey(MetaField.META_FIELD, DSL.name("KEY_meta_field_PRIMARY"), new TableField[] { MetaField.META_FIELD.ID }, true);
    public static final UniqueKey<MetaRowRecord> KEY_META_ROW_PRIMARY = Internal.createUniqueKey(MetaRow.META_ROW, DSL.name("KEY_meta_row_PRIMARY"), new TableField[] { MetaRow.META_ROW.ID }, true);
    public static final UniqueKey<MetaTableRecord> KEY_META_TABLE_PRIMARY = Internal.createUniqueKey(MetaTable.META_TABLE, DSL.name("KEY_meta_table_PRIMARY"), new TableField[] { MetaTable.META_TABLE.ID }, true);
}
