/*
 * This file is generated by jOOQ.
 */
package com.pp.jooq.model;


import com.pp.jooq.model.tables.MetaData;
import com.pp.jooq.model.tables.MetaField;
import com.pp.jooq.model.tables.MetaRow;
import com.pp.jooq.model.tables.MetaTable;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.15"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Meta extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>meta</code>
     */
    public static final Meta META = new Meta();

    /**
     * The table <code>meta.meta_data</code>.
     */
    public final MetaData META_DATA = MetaData.META_DATA;

    /**
     * The table <code>meta.meta_field</code>.
     */
    public final MetaField META_FIELD = MetaField.META_FIELD;

    /**
     * The table <code>meta.meta_row</code>.
     */
    public final MetaRow META_ROW = MetaRow.META_ROW;

    /**
     * The table <code>meta.meta_table</code>.
     */
    public final MetaTable META_TABLE = MetaTable.META_TABLE;

    /**
     * No further instances allowed
     */
    private Meta() {
        super("meta", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            MetaData.META_DATA,
            MetaField.META_FIELD,
            MetaRow.META_ROW,
            MetaTable.META_TABLE);
    }
}
