/*
 * This file is generated by jOOQ.
 */
package com.pp.jooq.model.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.15"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MetaField implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long   id;
    private Long   tableId;
    private String name;
    private String type;
    private String comment;
    private Byte   nullable;

    public MetaField() {}

    public MetaField(MetaField value) {
        this.id = value.id;
        this.tableId = value.tableId;
        this.name = value.name;
        this.type = value.type;
        this.comment = value.comment;
        this.nullable = value.nullable;
    }

    public MetaField(
        Long   id,
        Long   tableId,
        String name,
        String type,
        String comment,
        Byte   nullable
    ) {
        this.id = id;
        this.tableId = tableId;
        this.name = name;
        this.type = type;
        this.comment = comment;
        this.nullable = nullable;
    }

    /**
     * Getter for <code>meta.meta_field.id</code>. 主键
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>meta.meta_field.id</code>. 主键
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>meta.meta_field.table_id</code>. 关联的表ID
     */
    public Long getTableId() {
        return this.tableId;
    }

    /**
     * Setter for <code>meta.meta_field.table_id</code>. 关联的表ID
     */
    public void setTableId(Long tableId) {
        this.tableId = tableId;
    }

    /**
     * Getter for <code>meta.meta_field.name</code>. 字段名称
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>meta.meta_field.name</code>. 字段名称
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>meta.meta_field.type</code>. 字段类型
     */
    public String getType() {
        return this.type;
    }

    /**
     * Setter for <code>meta.meta_field.type</code>. 字段类型
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Getter for <code>meta.meta_field.comment</code>. 字段描述
     */
    public String getComment() {
        return this.comment;
    }

    /**
     * Setter for <code>meta.meta_field.comment</code>. 字段描述
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * Getter for <code>meta.meta_field.nullable</code>. 是否可空
     */
    public Byte getNullable() {
        return this.nullable;
    }

    /**
     * Setter for <code>meta.meta_field.nullable</code>. 是否可空
     */
    public void setNullable(Byte nullable) {
        this.nullable = nullable;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final MetaField other = (MetaField) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (tableId == null) {
            if (other.tableId != null)
                return false;
        }
        else if (!tableId.equals(other.tableId))
            return false;
        if (name == null) {
            if (other.name != null)
                return false;
        }
        else if (!name.equals(other.name))
            return false;
        if (type == null) {
            if (other.type != null)
                return false;
        }
        else if (!type.equals(other.type))
            return false;
        if (comment == null) {
            if (other.comment != null)
                return false;
        }
        else if (!comment.equals(other.comment))
            return false;
        if (nullable == null) {
            if (other.nullable != null)
                return false;
        }
        else if (!nullable.equals(other.nullable))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.tableId == null) ? 0 : this.tableId.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.type == null) ? 0 : this.type.hashCode());
        result = prime * result + ((this.comment == null) ? 0 : this.comment.hashCode());
        result = prime * result + ((this.nullable == null) ? 0 : this.nullable.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MetaField (");

        sb.append(id);
        sb.append(", ").append(tableId);
        sb.append(", ").append(name);
        sb.append(", ").append(type);
        sb.append(", ").append(comment);
        sb.append(", ").append(nullable);

        sb.append(")");
        return sb.toString();
    }
}
