/*
 * This file is generated by jOOQ.
 */
package com.pp.jooq.model.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.15"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MetaRow implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long   id;
    private Long   createTime;
    private Long   updateTime;
    private String creator;
    private String operator;
    private Long   tableId;

    public MetaRow() {}

    public MetaRow(MetaRow value) {
        this.id = value.id;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
        this.creator = value.creator;
        this.operator = value.operator;
        this.tableId = value.tableId;
    }

    public MetaRow(
        Long   id,
        Long   createTime,
        Long   updateTime,
        String creator,
        String operator,
        Long   tableId
    ) {
        this.id = id;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.creator = creator;
        this.operator = operator;
        this.tableId = tableId;
    }

    /**
     * Getter for <code>meta.meta_row.id</code>. 主键
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>meta.meta_row.id</code>. 主键
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>meta.meta_row.create_time</code>. 创建时间
     */
    public Long getCreateTime() {
        return this.createTime;
    }

    /**
     * Setter for <code>meta.meta_row.create_time</code>. 创建时间
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * Getter for <code>meta.meta_row.update_time</code>. 更新时间
     */
    public Long getUpdateTime() {
        return this.updateTime;
    }

    /**
     * Setter for <code>meta.meta_row.update_time</code>. 更新时间
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * Getter for <code>meta.meta_row.creator</code>. 创建人
     */
    public String getCreator() {
        return this.creator;
    }

    /**
     * Setter for <code>meta.meta_row.creator</code>. 创建人
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * Getter for <code>meta.meta_row.operator</code>. 更新人
     */
    public String getOperator() {
        return this.operator;
    }

    /**
     * Setter for <code>meta.meta_row.operator</code>. 更新人
     */
    public void setOperator(String operator) {
        this.operator = operator;
    }

    /**
     * Getter for <code>meta.meta_row.table_id</code>. 关联的表ID
     */
    public Long getTableId() {
        return this.tableId;
    }

    /**
     * Setter for <code>meta.meta_row.table_id</code>. 关联的表ID
     */
    public void setTableId(Long tableId) {
        this.tableId = tableId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final MetaRow other = (MetaRow) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (createTime == null) {
            if (other.createTime != null)
                return false;
        }
        else if (!createTime.equals(other.createTime))
            return false;
        if (updateTime == null) {
            if (other.updateTime != null)
                return false;
        }
        else if (!updateTime.equals(other.updateTime))
            return false;
        if (creator == null) {
            if (other.creator != null)
                return false;
        }
        else if (!creator.equals(other.creator))
            return false;
        if (operator == null) {
            if (other.operator != null)
                return false;
        }
        else if (!operator.equals(other.operator))
            return false;
        if (tableId == null) {
            if (other.tableId != null)
                return false;
        }
        else if (!tableId.equals(other.tableId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.createTime == null) ? 0 : this.createTime.hashCode());
        result = prime * result + ((this.updateTime == null) ? 0 : this.updateTime.hashCode());
        result = prime * result + ((this.creator == null) ? 0 : this.creator.hashCode());
        result = prime * result + ((this.operator == null) ? 0 : this.operator.hashCode());
        result = prime * result + ((this.tableId == null) ? 0 : this.tableId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MetaRow (");

        sb.append(id);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(creator);
        sb.append(", ").append(operator);
        sb.append(", ").append(tableId);

        sb.append(")");
        return sb.toString();
    }
}
