/*
 * This file is generated by jOOQ.
 */
package com.pp.jooq.model.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.15"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MetaData implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long   id;
    private Long   rowId;
    private Long   fieldId;
    private String fieldValue;
    private Byte   deleted;

    public MetaData() {}

    public MetaData(MetaData value) {
        this.id = value.id;
        this.rowId = value.rowId;
        this.fieldId = value.fieldId;
        this.fieldValue = value.fieldValue;
        this.deleted = value.deleted;
    }

    public MetaData(
        Long   id,
        Long   rowId,
        Long   fieldId,
        String fieldValue,
        Byte   deleted
    ) {
        this.id = id;
        this.rowId = rowId;
        this.fieldId = fieldId;
        this.fieldValue = fieldValue;
        this.deleted = deleted;
    }

    /**
     * Getter for <code>meta.meta_data.id</code>. 主键
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>meta.meta_data.id</code>. 主键
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>meta.meta_data.row_id</code>. 行ID
     */
    public Long getRowId() {
        return this.rowId;
    }

    /**
     * Setter for <code>meta.meta_data.row_id</code>. 行ID
     */
    public void setRowId(Long rowId) {
        this.rowId = rowId;
    }

    /**
     * Getter for <code>meta.meta_data.field_id</code>. 字段ID
     */
    public Long getFieldId() {
        return this.fieldId;
    }

    /**
     * Setter for <code>meta.meta_data.field_id</code>. 字段ID
     */
    public void setFieldId(Long fieldId) {
        this.fieldId = fieldId;
    }

    /**
     * Getter for <code>meta.meta_data.field_value</code>. 字段值
     */
    public String getFieldValue() {
        return this.fieldValue;
    }

    /**
     * Setter for <code>meta.meta_data.field_value</code>. 字段值
     */
    public void setFieldValue(String fieldValue) {
        this.fieldValue = fieldValue;
    }

    /**
     * Getter for <code>meta.meta_data.deleted</code>. 是否删除
     */
    public Byte getDeleted() {
        return this.deleted;
    }

    /**
     * Setter for <code>meta.meta_data.deleted</code>. 是否删除
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final MetaData other = (MetaData) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (rowId == null) {
            if (other.rowId != null)
                return false;
        }
        else if (!rowId.equals(other.rowId))
            return false;
        if (fieldId == null) {
            if (other.fieldId != null)
                return false;
        }
        else if (!fieldId.equals(other.fieldId))
            return false;
        if (fieldValue == null) {
            if (other.fieldValue != null)
                return false;
        }
        else if (!fieldValue.equals(other.fieldValue))
            return false;
        if (deleted == null) {
            if (other.deleted != null)
                return false;
        }
        else if (!deleted.equals(other.deleted))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.rowId == null) ? 0 : this.rowId.hashCode());
        result = prime * result + ((this.fieldId == null) ? 0 : this.fieldId.hashCode());
        result = prime * result + ((this.fieldValue == null) ? 0 : this.fieldValue.hashCode());
        result = prime * result + ((this.deleted == null) ? 0 : this.deleted.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MetaData (");

        sb.append(id);
        sb.append(", ").append(rowId);
        sb.append(", ").append(fieldId);
        sb.append(", ").append(fieldValue);
        sb.append(", ").append(deleted);

        sb.append(")");
        return sb.toString();
    }
}
