/*
 * This file is generated by jOOQ.
 */
package com.pp.jooq.model.tables.records;


import com.pp.jooq.model.tables.MetaField;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.15"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MetaFieldRecord extends UpdatableRecordImpl<MetaFieldRecord> implements Record6<Long, Long, String, String, String, Byte> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>meta.meta_field.id</code>. 主键
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>meta.meta_field.id</code>. 主键
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>meta.meta_field.table_id</code>. 关联的表ID
     */
    public void setTableId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>meta.meta_field.table_id</code>. 关联的表ID
     */
    public Long getTableId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>meta.meta_field.name</code>. 字段名称
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>meta.meta_field.name</code>. 字段名称
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>meta.meta_field.type</code>. 字段类型
     */
    public void setType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>meta.meta_field.type</code>. 字段类型
     */
    public String getType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>meta.meta_field.comment</code>. 字段描述
     */
    public void setComment(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>meta.meta_field.comment</code>. 字段描述
     */
    public String getComment() {
        return (String) get(4);
    }

    /**
     * Setter for <code>meta.meta_field.nullable</code>. 是否可空
     */
    public void setNullable(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>meta.meta_field.nullable</code>. 是否可空
     */
    public Byte getNullable() {
        return (Byte) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Long, String, String, String, Byte> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, Long, String, String, String, Byte> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return MetaField.META_FIELD.ID;
    }

    @Override
    public Field<Long> field2() {
        return MetaField.META_FIELD.TABLE_ID;
    }

    @Override
    public Field<String> field3() {
        return MetaField.META_FIELD.NAME;
    }

    @Override
    public Field<String> field4() {
        return MetaField.META_FIELD.TYPE;
    }

    @Override
    public Field<String> field5() {
        return MetaField.META_FIELD.COMMENT;
    }

    @Override
    public Field<Byte> field6() {
        return MetaField.META_FIELD.NULLABLE;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getTableId();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public String component4() {
        return getType();
    }

    @Override
    public String component5() {
        return getComment();
    }

    @Override
    public Byte component6() {
        return getNullable();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getTableId();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public String value4() {
        return getType();
    }

    @Override
    public String value5() {
        return getComment();
    }

    @Override
    public Byte value6() {
        return getNullable();
    }

    @Override
    public MetaFieldRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public MetaFieldRecord value2(Long value) {
        setTableId(value);
        return this;
    }

    @Override
    public MetaFieldRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public MetaFieldRecord value4(String value) {
        setType(value);
        return this;
    }

    @Override
    public MetaFieldRecord value5(String value) {
        setComment(value);
        return this;
    }

    @Override
    public MetaFieldRecord value6(Byte value) {
        setNullable(value);
        return this;
    }

    @Override
    public MetaFieldRecord values(Long value1, Long value2, String value3, String value4, String value5, Byte value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MetaFieldRecord
     */
    public MetaFieldRecord() {
        super(MetaField.META_FIELD);
    }

    /**
     * Create a detached, initialised MetaFieldRecord
     */
    public MetaFieldRecord(Long id, Long tableId, String name, String type, String comment, Byte nullable) {
        super(MetaField.META_FIELD);

        setId(id);
        setTableId(tableId);
        setName(name);
        setType(type);
        setComment(comment);
        setNullable(nullable);
    }
}
