/*
 * This file is generated by jOOQ.
 */
package com.pp.jooq.model.tables.records;


import com.pp.jooq.model.tables.MetaData;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.15"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MetaDataRecord extends UpdatableRecordImpl<MetaDataRecord> implements Record5<Long, Long, Long, String, Byte> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>meta.meta_data.id</code>. 主键
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>meta.meta_data.id</code>. 主键
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>meta.meta_data.row_id</code>. 行ID
     */
    public void setRowId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>meta.meta_data.row_id</code>. 行ID
     */
    public Long getRowId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>meta.meta_data.field_id</code>. 字段ID
     */
    public void setFieldId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>meta.meta_data.field_id</code>. 字段ID
     */
    public Long getFieldId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>meta.meta_data.field_value</code>. 字段值
     */
    public void setFieldValue(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>meta.meta_data.field_value</code>. 字段值
     */
    public String getFieldValue() {
        return (String) get(3);
    }

    /**
     * Setter for <code>meta.meta_data.deleted</code>. 是否删除
     */
    public void setDeleted(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>meta.meta_data.deleted</code>. 是否删除
     */
    public Byte getDeleted() {
        return (Byte) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, Long, Long, String, Byte> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, Long, Long, String, Byte> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return MetaData.META_DATA.ID;
    }

    @Override
    public Field<Long> field2() {
        return MetaData.META_DATA.ROW_ID;
    }

    @Override
    public Field<Long> field3() {
        return MetaData.META_DATA.FIELD_ID;
    }

    @Override
    public Field<String> field4() {
        return MetaData.META_DATA.FIELD_VALUE;
    }

    @Override
    public Field<Byte> field5() {
        return MetaData.META_DATA.DELETED;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getRowId();
    }

    @Override
    public Long component3() {
        return getFieldId();
    }

    @Override
    public String component4() {
        return getFieldValue();
    }

    @Override
    public Byte component5() {
        return getDeleted();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getRowId();
    }

    @Override
    public Long value3() {
        return getFieldId();
    }

    @Override
    public String value4() {
        return getFieldValue();
    }

    @Override
    public Byte value5() {
        return getDeleted();
    }

    @Override
    public MetaDataRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public MetaDataRecord value2(Long value) {
        setRowId(value);
        return this;
    }

    @Override
    public MetaDataRecord value3(Long value) {
        setFieldId(value);
        return this;
    }

    @Override
    public MetaDataRecord value4(String value) {
        setFieldValue(value);
        return this;
    }

    @Override
    public MetaDataRecord value5(Byte value) {
        setDeleted(value);
        return this;
    }

    @Override
    public MetaDataRecord values(Long value1, Long value2, Long value3, String value4, Byte value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MetaDataRecord
     */
    public MetaDataRecord() {
        super(MetaData.META_DATA);
    }

    /**
     * Create a detached, initialised MetaDataRecord
     */
    public MetaDataRecord(Long id, Long rowId, Long fieldId, String fieldValue, Byte deleted) {
        super(MetaData.META_DATA);

        setId(id);
        setRowId(rowId);
        setFieldId(fieldId);
        setFieldValue(fieldValue);
        setDeleted(deleted);
    }
}
