/*
 * This file is generated by jOOQ.
 */
package com.pp.jooq.model.tables.records;


import com.pp.jooq.model.tables.MetaTable;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.15"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MetaTableRecord extends UpdatableRecordImpl<MetaTableRecord> implements Record9<Long, Long, Long, String, String, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>meta.meta_table.id</code>. 主键
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>meta.meta_table.id</code>. 主键
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>meta.meta_table.create_time</code>. 创建时间
     */
    public void setCreateTime(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>meta.meta_table.create_time</code>. 创建时间
     */
    public Long getCreateTime() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>meta.meta_table.update_time</code>. 更新时间
     */
    public void setUpdateTime(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>meta.meta_table.update_time</code>. 更新时间
     */
    public Long getUpdateTime() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>meta.meta_table.creator</code>. 创建人
     */
    public void setCreator(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>meta.meta_table.creator</code>. 创建人
     */
    public String getCreator() {
        return (String) get(3);
    }

    /**
     * Setter for <code>meta.meta_table.operator</code>. 更新人
     */
    public void setOperator(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>meta.meta_table.operator</code>. 更新人
     */
    public String getOperator() {
        return (String) get(4);
    }

    /**
     * Setter for <code>meta.meta_table.table_name</code>. 表名
     */
    public void setTableName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>meta.meta_table.table_name</code>. 表名
     */
    public String getTableName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>meta.meta_table.cn_name</code>. 表别名
     */
    public void setCnName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>meta.meta_table.cn_name</code>. 表别名
     */
    public String getCnName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>meta.meta_table.desc</code>. 描述信息
     */
    public void setDesc(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>meta.meta_table.desc</code>. 描述信息
     */
    public String getDesc() {
        return (String) get(7);
    }

    /**
     * Setter for <code>meta.meta_table.namespace</code>. 空间唯一标识
     */
    public void setNamespace(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>meta.meta_table.namespace</code>. 空间唯一标识
     */
    public String getNamespace() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, Long, Long, String, String, String, String, String, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Long, Long, Long, String, String, String, String, String, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return MetaTable.META_TABLE.ID;
    }

    @Override
    public Field<Long> field2() {
        return MetaTable.META_TABLE.CREATE_TIME;
    }

    @Override
    public Field<Long> field3() {
        return MetaTable.META_TABLE.UPDATE_TIME;
    }

    @Override
    public Field<String> field4() {
        return MetaTable.META_TABLE.CREATOR;
    }

    @Override
    public Field<String> field5() {
        return MetaTable.META_TABLE.OPERATOR;
    }

    @Override
    public Field<String> field6() {
        return MetaTable.META_TABLE.TABLE_NAME;
    }

    @Override
    public Field<String> field7() {
        return MetaTable.META_TABLE.CN_NAME;
    }

    @Override
    public Field<String> field8() {
        return MetaTable.META_TABLE.DESC;
    }

    @Override
    public Field<String> field9() {
        return MetaTable.META_TABLE.NAMESPACE;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getCreateTime();
    }

    @Override
    public Long component3() {
        return getUpdateTime();
    }

    @Override
    public String component4() {
        return getCreator();
    }

    @Override
    public String component5() {
        return getOperator();
    }

    @Override
    public String component6() {
        return getTableName();
    }

    @Override
    public String component7() {
        return getCnName();
    }

    @Override
    public String component8() {
        return getDesc();
    }

    @Override
    public String component9() {
        return getNamespace();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getCreateTime();
    }

    @Override
    public Long value3() {
        return getUpdateTime();
    }

    @Override
    public String value4() {
        return getCreator();
    }

    @Override
    public String value5() {
        return getOperator();
    }

    @Override
    public String value6() {
        return getTableName();
    }

    @Override
    public String value7() {
        return getCnName();
    }

    @Override
    public String value8() {
        return getDesc();
    }

    @Override
    public String value9() {
        return getNamespace();
    }

    @Override
    public MetaTableRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public MetaTableRecord value2(Long value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public MetaTableRecord value3(Long value) {
        setUpdateTime(value);
        return this;
    }

    @Override
    public MetaTableRecord value4(String value) {
        setCreator(value);
        return this;
    }

    @Override
    public MetaTableRecord value5(String value) {
        setOperator(value);
        return this;
    }

    @Override
    public MetaTableRecord value6(String value) {
        setTableName(value);
        return this;
    }

    @Override
    public MetaTableRecord value7(String value) {
        setCnName(value);
        return this;
    }

    @Override
    public MetaTableRecord value8(String value) {
        setDesc(value);
        return this;
    }

    @Override
    public MetaTableRecord value9(String value) {
        setNamespace(value);
        return this;
    }

    @Override
    public MetaTableRecord values(Long value1, Long value2, Long value3, String value4, String value5, String value6, String value7, String value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MetaTableRecord
     */
    public MetaTableRecord() {
        super(MetaTable.META_TABLE);
    }

    /**
     * Create a detached, initialised MetaTableRecord
     */
    public MetaTableRecord(Long id, Long createTime, Long updateTime, String creator, String operator, String tableName, String cnName, String desc, String namespace) {
        super(MetaTable.META_TABLE);

        setId(id);
        setCreateTime(createTime);
        setUpdateTime(updateTime);
        setCreator(creator);
        setOperator(operator);
        setTableName(tableName);
        setCnName(cnName);
        setDesc(desc);
        setNamespace(namespace);
    }
}
